### ISSUE TITLE
MetaMask wallet support

### ISSUE THREAD

**Issue by agostbiro** [dbpunk-labs/db3.js#40]
Hi,

I'm wondering if there is an example that uses a MetaMask wallet?

**Comment by imotai** [comment]
@agostbiro Just give me some time and I will give you an example

**Comment by imotai** [comment]
@agostbiro  you can see the example here https://github.com/dbpunk-labs/db3.js/blob/main/examples/helloworld/src/App.tsx

**Comment by imotai** [comment]
A runnable version can be found here https://replit.com/@imotai/db3-playground-with-metamask?v=1

**Comment by agostbiro** [comment]
Thanks @imotai , I tested the runnable version and it works great!
